### ISSUE TITLE
Analyse Appache Log files

### ISSUE THREAD

**Issue by hofmannc** [hofmannc/Load-Tests-PubMan#4]
Please analyse appache log files of 14.11. and 20.10. (sent by Benjamin by E-Mail).
Goal: get average user data to be able to start with average load testcases.

Please research on the following questions:

How does an average bot request strategy look like? (severe attacks with pauses? or just spread over th whole day? Um welche Tageszeiten treten sie vermehrt auf?)

When are batchjobs released/imported? which sizes? (amount of items/ amount of data volume)

Please complete the yellow lines in the excel-sheet.
[analytics.xlsx](https://github.com/hofmannc/Load-Tests-PubMan/files/597641/analytics.xlsx)

**Comment by hofmannc** [comment]
I added your categries to my excel-sheet -  Please extract the log data for all dates given in the excel-sheet.
 - 28.11. : please see new table of 161128

If you find out that 25 samples are not sufficient for making conclusions on the data, please feel free to extract data of more dates -> please make sure that date is always later than 01.01.2016 and (if possible) monday - friday

Please also continue investigating about the patterns:
* How does an average bot request strategy look like? 
* Size (items/data volume) and "preferred occurrance" of batch jobs. If matching with Pubman too complicated we'll ask Martin/Matthias for reasonable sizes of batchjobs. --> data will be taken from dev team

**Comment by aapetrova** [comment]
Out of the Apache logs we can gather information about:

1. how many users perform batch import during the day
2. how many batch jobs were performed
3. how many items every batch job contains

We cannot infer the size of separate imports just from the logs. A possibility is to look up the imports by ID in the PubMan database.

**Comment by hofmannc** [comment]
Average Thinktime of User:
At this stage we cannot extract reliable data for the thinktime of the user (time between two clicks). 
According to Reisner, thinktime is used as a random variable, so we will work with this approach for a first step.
submit/release - Min: 2 s Mx 20 sec
search - Min 2 sec max 10 sec

If we need more realistic data, we should contact Matthias and Gudrun to log the thinktime for 24 h.

**Comment by aapetrova** [comment]
Average throughput for batch import is 583 kbits/s.
