### ISSUE TITLE
Explore jmeter's options for comparing test results automatically

### ISSUE THREAD

**Issue by hofmannc** [hofmannc/Load-Tests-PubMan#5]
A requirement of the developer's is the comparability of the load test results.

Please find out about 
1.which parameters are generally relevant for comparing after a I. dev CI load test II. qa-load test
2.which Jmeter parameters are easily compareable?
3.in which formats can we provide the results?

please write down the answers in this ticket

**Comment by aapetrova** [comment]
1. the most important parameter is the average response time, though all other mentioned below should be comparable after every test
2. elapsed time, throughput, latency (time to first response), error count
3. JMeter exports results in .xml and .csv formats or as an image
